### ISSUE TITLE
Kernel won't install

### ISSUE THREAD

**Issue by melinstagibson** [RadeonOpenCompute/ROCK-Kernel-Driver#39] opened 2017-12-22 17:42 UTC
So this is most likely a very beginner-ish issue but i can't get the rocm kernel to install on my system.
i tried to follow the procedure on ubuntu 16.04 while on kernel 4.4, 4.11 and 4.14 but i was never able to get the rocm kernel installed, am i missing something obvious?

https://github.com/RadeonOpenCompute/ROCm/wiki

i followed all the steps on that site, but the rocm kernel wont show up if i do dpkg --list | grep linux-image
and if i change the default line in grub to what is described in the wiki it will keep booting the default kernel.

**Comment by Yougmark** [comment] 2018-02-01 00:36
Don't know if this is resolved already.  But the wiki you were following doesn't let you install the kernel, but instead a few amd* kernel modules/drivers (amdgpu/amdkfd/...), and runtime libraries like libhsa\*runtime64\* (don't remember the exact name), libhsakmt.so, and so on.

If you want to install ROCK-kernel-driver for ROCm, refer to https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver

Good luck! And please close this issue if the problem is solved. Thanks!

**Closed** 2018-02-01 03:06 UTC
