### ISSUE TITLE
DKMS fail to compile: "Local GCC version 100202 does not match kernel compiler GCC version 100200"

### ISSUE THREAD

**Issue by skarmiglione** [RadeonOpenCompute/ROCK-Kernel-Driver#104] opened 2020-11-22 23:32 UTC
Hello there, here i go: I am triying to install rock dkms and his friends but it gave that log i will paste here, is there a way to get it working? is just the thing with the gcc version ? 

ProblemType: Package
DKMSBuildLog:
 DKMS make.log for amdgpu-3.9-17 for kernel 5.8.0-25-generic (x86_64)
 dom 22 nov 2020 04:43:22 -05
 make: se entra en el directorio '/usr/src/linux-headers-5.8.0-25-generic'
 /var/lib/dkms/amdgpu/3.9-17/build/Makefile:20: "Local GCC version 100202 does not match kernel compiler GCC version 100200"
 /var/lib/dkms/amdgpu/3.9-17/build/Makefile:21: "This may cause unexpected and hard-to-isolate compiler-related issues"
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/scheduler/sched_main.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_memory.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/main.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_drv.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/symbols.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_memory.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_ioctl.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_tt.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_device_cgroup.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_device.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/scheduler/sched_fence.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm_cache.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/scheduler/sched_entity.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_fence_array.o
   LD [M]  /var/lib/dkms/amdgpu/3.9-17/build/scheduler/amd-sched.o
   AR      /var/lib/dkms/amdgpu/3.9-17/build/built-in.a
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_fence.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_util.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_io.o
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_fence.c:30:1: warning: ‘dma_fence_test_signaled_any’ defined but not used [-Wunused-function]
    30 | dma_fence_test_signaled_any(struct dma_fence **fences, uint32_t count,
       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_kthread.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_kms.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_mm.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_pci.o
 /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.c: In function ‘ttm_bo_vm_fault_idle’:
/var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.c:76:24: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
    76 |   up_read(&vma->vm_mm->mmap_sem);
       |                        ^~~~~~~~
       |                        mmap_base
 /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.c: In function ‘amdttm_bo_vm_reserve’:
 /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.c:155:26: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
   155 |     up_read(&vma->vm_mm->mmap_sem);
       |                          ^~~~~~~~
       |                          mmap_base
 make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.o] Error 1
 make[1]: *** [scripts/Makefile.build:519: /var/lib/dkms/amdgpu/3.9-17/build/ttm] Error 2
 make[1]: *** Se espera a que terminen otras tareas....
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_atombios.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_perf_event.o
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_pci.c: In function ‘amdkcl_pci_init’:
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_pci.c:103:84: warning: passing argument 2 of ‘amdkcl_fp_setup’ discards ‘const’ qualifier from pointer target type [>
   103 |  _kcl_pcie_link_speed = (const unsigned char *) amdkcl_fp_setup("pcie_link_speed", _kcl_pcie_link_speed_stub);
       |                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_pci.c:4:
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_common.h:12:63: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
    12 | static inline void *amdkcl_fp_setup(const char *symbol, void *fp_stup)
       |                                                         ~~~~~~^~~~~~~
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_reservation.o
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_kms.c: In function ‘amdgpu_driver_load_kms’:
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_kms.c:202:38: error: ‘DPM_FLAG_NEVER_SKIP’ undeclared (first use in this function)
   202 |    dev_pm_set_driver_flags(dev->dev, DPM_FLAG_NEVER_SKIP);
       |                                      ^~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_kms.c:202:38: note: each undeclared identifier is reported only once for each function it appears in
 make[2]: *** [scripts/Makefile.build:290: /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu/amdgpu_kms.o] Error 1
 make[2]: *** Se espera a que terminen otras tareas....
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_suspend.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_workqueue.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_seq_file.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_connector.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_backlight.o
 make[1]: *** [scripts/Makefile.build:519: /var/lib/dkms/amdgpu/3.9-17/build/amd/amdgpu] Error 2
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm_atomic_helper.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm_crtc.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm_fb.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm_modeset_lock.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_drm_modes.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/kcl_mn.o
   CC [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/dma-buf/dma-resv.o
   LD [M]  /var/lib/dkms/amdgpu/3.9-17/build/amd/amdkcl/amdkcl.o
 make: *** [Makefile:1780: /var/lib/dkms/amdgpu/3.9-17/build] Error 2
 make: se sale del directorio '/usr/src/linux-headers-5.8.0-25-generic'
DKMSKernelVersion: 5.8.0-25-generic
Date: Sun Nov 22 04:44:07 2020
DuplicateSignature: dkms:rock-dkms:1:3.9-17:/var/lib/dkms/amdgpu/3.9-17/build/ttm/ttm_bo_vm.c:76:24: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you>
Package: rock-dkms 1:3.9-17
PackageVersion: 1:3.9-17
SourcePackage: rock-dkms
Title: rock-dkms 1:3.9-17: amdgpu kernel module failed to build

very sad if it only work with old kernels :C maybe i am having the same problem with amdgpu pro? :'c

**Comment by kentrussell** [comment] 2020-11-23 12:44
The compiler warning isn't a critical issue, it just helps to identify quirks when the compiler for the kernel doesn't match the compiler on your system.

The big thing here is that ROCm 3.9 is based on the 5.6 kernel, so there isn't support for 5.7 and 5.8 changes in this release. You can refer to the Release Notes on https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#amd-rocm-release-notes-v3-9-0 regarding kernel support. This should be addressed in ROCm 4.0, as the upcoming 3.10 release will also be based on the 5.6 kernel with some critical fixes added. 

The amdgpu-pro kernel will have the same issue until they move to the 5.9-based branch as well (we share a common code base). Their support list is on their Release Notes, but they don't have the 5.8 kernel as part of their support list in their last release (20.40). 

The core of the issue is that the 5.7 kernel renamed mmap_sem to mmap_lock, so any references to mmap_sem in the ROCm/amdgpu-pro kernel won't work as-is. The first new ROCm or amdgpu-pro release of 2021 will have this issue addressed, in line with other kernel compatibility changes that we provide in our DKMS packages. 

If you want to try to get it working yourself, you can always edit the DKMS files and do the rename yourself (then rebuild and install), though it's a bit of work and is not officially supported by ROCm. But with a DKMS install, you have the source code on your local machine so you can definitely try to tinker around if you wish, bearing in mind that you are using an untested kernel config so there may be other bugs along the way.

**Closed by kentrussell** 2020-11-23 12:44 UTC

**Comment by iqoptionizator** [comment] 2024-02-16 17:09
i have some issue with ubuntu 22.04.3 and kernel 5.19 or 6.5

**Comment by kentrussell** [comment] 2024-02-16 17:37
Is this compiler warning message causing an issue? It just means that the compiler used to build your kernel is different from the compiler on your system which is compiling the DKMS code.

**Comment by iqoptionizator** [comment] 2024-02-16 18:18
i think not in compiler version issue, but some functions get error when make, like this:
make[2]: *** [scripts/Makefile.build:257: /var/lib/dkms/amdgpu/6.3.6-1718217.20.04/build/amd/amdkcl/kcl_drm_fb.o] Error 1
or this 
/var/lib/dkms/amdgpu/6.3.6-1718217.20.04/build/include/kcl/kcl_drm_dp_cec.h:67:53: error: passing argument 2 of ‘drm_dp_cec_register_connector’ from incompatible pointer type

i probe 3 versions of kernel: 5.19, 6.2 and 6.5 and latest ROCM driver from site:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/tutorial/quick-start.html

amdgpu-dkms DKMS module install failure ):
I think it's time to take your advice and rewrite a number of functions (:

**Comment by FlorianHeigl** [comment] 2025-04-08 21:14
@kentrussell it will cause issues as soon as there's something that's incompatible.
(i.e. i had crashing X on Rocky 8.9 with amdgpu, used mainline kernel from elrepo or something, got this error and also a dkms failure, the error message was important for understanding what was wrong. hope, in that case)
